---
- name: Hello World Playbook
  hosts: all
  become: false  # Set to true if you need sudo
  connection: local
  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
        msg: "Hello, World!"
